<?php

namespace App\ApiGen;

use ApiGen\Index\Index;
use ApiGen\Renderer\Latte\LatteRenderer;
use ApiGen\Renderer\Latte\Template\ConfigParameters;

class CustomLatteRenderer extends LatteRenderer
{
    public function renderIndex(Index $index, ConfigParameters $config): string
    {
        return parent::renderIndex($index, $config); // TODO: Change the autogenerated stub
    }
}
